// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:cbb675a9-885e-44f1-baa5-4cb0243db6a0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tFhRE5TRe",
    "aws_user_pools_web_client_id": "1qqt8uh146epjiotlqs27l6ml1",
    "aws_appsync_graphqlEndpoint": "https://kc3txk6tkrcarexicqh35tlxhq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qzdc77j6fvantcvj2tj7bw5tmm"
};


export default awsmobile;
